### ISSUE TITLE
[BUG] small list of features not currently working

### ISSUE THREAD

**Issue by MrNewb** [Qbox-project/qbx-policejob#14]
### Summary

[BUG] small list of features not currently working

### Reproduction

Descriptions are missing in a few places for the ox inventory compatibility, I pred one in an easy way to add this but there are a few others that I just don't know what to do with. 

client\evidence.lua -- evidence:client:AddCasing
info from qb-inventory for the serial is not pulling the guns serial
https://github.com/Qbox-project/qbx-policejob/blob/ca9ec98b601e5725b9b8f350222e71f84ab7a07a/client/evidence.lua#L238

server\main.lua  --- evidence:server:AddBlooddropToInventory 
this is not working but there is an amazing snippet in the discord from sudokill9#2754   --- I didn't want to pr someone elses work and to fully utilize it requires a edit to ox_inventory\data\items.lua
https://discord.com/channels/1012753553418354748/1031968831595352085/1075428193219125340

client\interactions.lua   ---  police:client:SearchPlayer
there's a few methods posted in the discord but for the most part I've just used exports.ox_inventory:openNearbyInventory()
https://github.com/Qbox-project/qbx-policejob/blob/ca9ec98b601e5725b9b8f350222e71f84ab7a07a/client/interactions.lua#L143

A majority of it seems to work, just posting some issues in case they haven't been noticed.

### Expected behavior

sweet sweet qbox

### Actual behavior

sweet sweet qbox

### Last Updated

today

### Custom Resources

meh

### Resource Rename

qb-policejob

**Comment by ChatDisabled** [comment]
@MrNewb There have been some PRs regarding multiple topics in here since the creation of the issue. Could you retest some of these and if needed make another issue? Thanks.
